version: "3.0"
   
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=check_print_pages
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/page_content
    ports:
      - "8000:8000"
    depends_on:
      - db

