# Generated by Django 3.2 on 2021-10-30 16:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('show_title', models.BooleanField(default=True, verbose_name='show title?')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled?')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
    ]
